### ISSUE TITLE
Confusion with the training setting

### ISSUE THREAD

**Issue by Scalsol** [hkzhang95/DynamicRCNN#1]
I notice that when you are using multi-scale training you would extend the training time by `1.5x`. So why not directly name these configs as `3x` config? Also as you extend your training time, I think it's better to clarify this in the paper for fair comparision...

**Comment by hkzhang95** [comment]
Thanks for your suggestions.

1. The names of configs are mainly a matter of personal habits. I will rename them to avoid possible confusion.
2. As mentioned in the paper, various settings are adopted by different detectors, so we can only try to make a fair comparison. On one hand, we provide detailed comparisons between Dynamic R-CNN and Faster R-CNN under various settings in Table 2 to validate our effectiveness. On the other hand, to fairly compare Dynamic R-CNN* with TridentNet, when we adopt multi-scale training, we follow TridentNet which extends the training time by `1.5x`. I remember clarifying this setting in the paper, but maybe I delete the words by mistake. I will add such descriptions in the next version.
