### ISSUE TITLE
Synchronization between multiple gpu

### ISSUE THREAD

**Issue by TangAL0203** [hkzhang95/DynamicRCNN#2]
在代码中，计算rcnn_iou_new和rcnn_error_new只考虑到了单个GPU的样本，感觉这会造成一定统计的不稳定性，请问作者有考虑在多GPU之间进行一个同步吗？也就是rcnn_iou_new和rcnn_error_new的更新会考虑到整个batch的样本，而不是统计IMS_PER_GPU的样本

**Comment by hkzhang95** [comment]
Thanks for your question.

Actually, I noticed this issue when I was implementing Dynamic R-CNN. From my viewpoint, adopting the statistics across the whole batch (multiple GPUs) will be more robust. However, I had no quota at that time.

I will add this feature when I am available. Contributions are also welcome!
