### ISSUE TITLE
Questions about Fig. 5

### ISSUE THREAD

**Issue by TangAL0203** [hkzhang95/DynamicRCNN#3]
你好，我基于mmdetection实现了Dynamic-RCNN的训练策略，在训练过程中，我观察了IOU阈值和beta值的更新情况，具有以下特点：
1、iou阈值在前几个迭代过程中，就可以提升到0.6左右，后续的迭代，iou阈值一致在0.58范围内做上下波动。
2、beta值经过几次迭代之后，迅速从1下降到一个小于0.1的值，且在以后的迭代过程中，在这个值做小幅度的波动。
PS：上述的实验是同时采用了DLA和DSL，超参和论文保持一致。

从我的实验中，iou和beta值的变化和论文中的Fig. 5 情况差异很大，所以想请教一下论文中iou和beta值具体是怎么统计出来的，以及相应的实现细节？

**Comment by hkzhang95** [comment]
Thanks for your question.

1. I have also implemented Dynamic R-CNN using MMDetection. Here are some examples (update every 100 iterations using the average value):

```
Epoch [1][100/7330], current self.train_cfg.rcnn.assigner.pos_iou_thr: 0.4207725304114865
Epoch [1][200/7330], current self.train_cfg.rcnn.assigner.pos_iou_thr: 0.4912639345298521
Epoch [1][300/7330], current self.train_cfg.rcnn.assigner.pos_iou_thr: 0.516701815277338
Epoch [1][400/7330], current self.train_cfg.rcnn.assigner.pos_iou_thr: 0.5329994469508529
Epoch [1][500/7330], current self.train_cfg.rcnn.assigner.pos_iou_thr: 0.5378521626256406
```

From the observations above, the IoU threshold cannot increase so fast like "achieve 0.6 in just several iterations", so maybe you are doing some wrong calculations. The result is also similar using this codebase, and you can get the statistics easily by adding several lines in this [part](https://github.com/hkzhang95/DynamicRCNN/blob/master/models/zhanghongkai/dynamic_rcnn/coco/dynamic_rcnn_r50_fpn_1x/train.py#L191). Note that I use running mean strategy to smooth the curve in Fig. 5, so the values will be slightly lower.

2. I am not sure what detailed implementations you are asking. In each iteration, the k-th IoU and beta will be obtained like [this part](https://github.com/hkzhang95/DynamicRCNN/blob/master/models/zhanghongkai/dynamic_rcnn/coco/dynamic_rcnn_r50_fpn_1x/network.py#L160).

I hope these can solve your problem.

**Comment by TangAL0203** [comment]
谢谢你的回答，我回去check一下相关代码！
